export const fetchedData = [
  {
      "id": "1676290",
      "title": "Флюороген4",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002109064",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1630911938,
      "last_active": "18.11.2021 17:46",
      "last_active_rfc": "2021-11-18T17:46:18+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1447778",
      "title": "Васильев Василий Васильевич",
      "name": "Василий",
      "surname": "Васильев",
      "patronymic": "Васильевич",
      "phone": "79334445667",
      "email": "test40@test.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": "1",
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1676302",
      "title": "Флюороген7",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002109067",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1630912346,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1465310",
      "title": "qweq1e",
      "name": "Qweq1E",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "c121e@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": "125",
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1535184",
      "title": "Квася Вася S",
      "name": "Вася",
      "surname": "Квася",
      "patronymic": "S",
      "phone": "70000234234",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1605251022,
      "last_active": "15.02.2022 12:43",
      "last_active_rfc": "2022-02-15T12:43:55+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1466544",
      "title": "Василий Василь Васильев",
      "name": "Василь",
      "surname": "Василий",
      "patronymic": "Васильев",
      "phone": "",
      "email": "russu@mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "10.01.2020 16:14",
      "last_active_rfc": "2020-01-10T16:14:18+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": "2",
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "524908",
      "title": "Artem Eeee Eeee",
      "name": "Eeee",
      "surname": "Artem",
      "patronymic": "Eeee",
      "phone": "79655542233",
      "email": "d@59.ru",
      "avatar": "https://files.mysmartflat.ru/15183.jpg",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "21.02.2022 20:28",
      "last_active_rfc": "2022-02-21T20:28:54+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1561014",
      "title": "86838636268",
      "name": "86838636268",
      "surname": "",
      "patronymic": "",
      "phone": "75676557677",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1612090729,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1535183",
      "title": "Вася ВАся",
      "name": "Пётр",
      "surname": "Иванов",
      "patronymic": "Иванович",
      "phone": "70000000012",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1605250983,
      "last_active": "15.02.2022 12:42",
      "last_active_rfc": "2022-02-15T12:42:37+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": "",
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1676304",
      "title": "Флюгер Гехаймер XXL",
      "name": "Гехаймер",
      "surname": "Флюгер",
      "patronymic": "XXL",
      "phone": "70002109068",
      "email": "",
      "avatar": "https://files.mysmartflat.ru/25166.jpg",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1630912403,
      "last_active": "20.09.2021 15:39",
      "last_active_rfc": "2021-09-20T15:39:27+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "5"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1468971",
      "title": "пгнавеглва",
      "name": "Пгнавеглва",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "nafistest3@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": "1",
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1578253",
      "title": "Александр Поломошнов",
      "name": "Александр",
      "surname": "Поломошнов",
      "patronymic": "",
      "phone": "70000005678",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1623830924,
      "last_active": "15.03.2021 14:14",
      "last_active_rfc": "2021-03-15T14:14:13+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": "тест",
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "866773",
      "title": "artemm Artem Artem",
      "name": "Artem",
      "surname": "artemm",
      "patronymic": "Artem",
      "phone": "",
      "email": "3test@test.ru",
      "avatar": "https://cndslctl.mysmartflat.ru/public-storage/f9463d0f-bbce-4cda-ba4c-60ef21690382.jpeg",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "31.12.2020 21:00",
      "last_active_rfc": "2020-12-31T21:00:09+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "2",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1597343",
      "title": "Тесткода",
      "name": "Тесткода",
      "surname": "",
      "patronymic": "",
      "phone": "70015008230",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1619575594,
      "last_active": "26.08.2021 10:55",
      "last_active_rfc": "2021-08-26T10:55:30+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1676326",
      "title": "Флюороген9",
      "name": "Флюороген",
      "surname": "",
      "patronymic": "",
      "phone": "70002109069",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1630912945,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1507119",
      "title": "Самойлов А.А.",
      "name": "А.а.",
      "surname": "Самойлов",
      "patronymic": "",
      "phone": "",
      "email": "samtest423@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1595313901,
      "last_active": "21.07.2020 15:19",
      "last_active_rfc": "2020-07-21T15:19:19+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1606211",
      "title": "Демонстрация Домофонии Нетрогать",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70019517535",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1624365009,
      "last_active": "29.07.2021 18:45",
      "last_active_rfc": "2021-07-29T18:45:36+05:00",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1676277",
      "title": "Флюороген2",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002109062",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 3",
      "apartment_id": "21678",
      "apartment_number": "3",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 3",
      "building_id": "721",
      "created_at": 1630911714,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [
          {
              "id": 1652,
              "account_number": "0000000000",
              "balance": 0,
              "company_title": "ООО \"УПРАВЛЯЮЩАЯ КОМПАНИЯ \"ЮНИКОРН-СЕРВИС\"",
              "service_title": "Коммунальные услуги",
              "last_operation_date": null
          }
      ],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1500847",
      "title": "Йцкенгшзххэжлорпавффвячмиьбюжххщшнекцыамитлджээдьипаа",
      "name": "Йцкенгшзххэжлорпавффвячмиьбюжххщшнекцыамитлджээдьипаа",
      "surname": "",
      "patronymic": "",
      "phone": "79005006463",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 12,
      "ownership_denominator": 13,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1591616538,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1550542",
      "title": "4080 datalost test",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70004134514",
      "email": "datalost@test.com",
      "avatar": "https://files.mysmartflat.ru/12627.png",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 1000,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1608611307,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": "Три восьмых!!",
      "status": [
          "1",
          "3"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1366789",
      "title": "RT3_UPD",
      "name": "Rt3_Upd",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "rt3@test.ru",
      "avatar": "https://files.mysmartflat.ru/2055.png",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": "210",
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1498604",
      "title": "Ружицкий Виктор Степанович",
      "name": "Виктор",
      "surname": "Ружицкий",
      "patronymic": "Степанович",
      "phone": "79023452221",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1588934975,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": "",
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1465307",
      "title": "TEST",
      "name": "Test",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "tegp34r2@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": "undefined",
      "has_debts": false,
      "size": "2",
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1560821",
      "title": "Приветов Иван Иванович",
      "name": "Иван",
      "surname": "Приветов",
      "patronymic": "Иванович",
      "phone": "70002992171",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1611983396,
      "last_active": "06.12.2021 22:22",
      "last_active_rfc": "2021-12-06T22:22:24+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1490132",
      "title": "Тест Аренды НЕ ТРОГАТЬ",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002123344",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1585293013,
      "last_active": "02.11.2020 11:26",
      "last_active_rfc": "2020-11-02T11:26:53+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1488053",
      "title": "wqef",
      "name": "Wqef",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "ghsdefe21@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1583898706,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1597079",
      "title": "Новенький Жилец Тестович",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70015226013",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1619504550,
      "last_active": "27.04.2021 16:40",
      "last_active_rfc": "2021-04-27T16:40:31+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1448074",
      "title": "fgfgf",
      "name": "Fgfgf",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "qwer@qwe.za",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1613704",
      "title": "Иванов Иван Иванович",
      "name": "Dmitriy",
      "surname": "Shraiber",
      "patronymic": "",
      "phone": "70007937379",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 4",
      "apartment_id": "21679",
      "apartment_number": "4",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 4",
      "building_id": "721",
      "created_at": 1623828742,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": "свыаыв",
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1615558",
      "title": "тест паролей 2",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70012564891",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1624266326,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1566424",
      "title": "Пьянков Владислав",
      "name": "Владислав",
      "surname": "Пьянков",
      "patronymic": "",
      "phone": "79082414091",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1613105647,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1501779",
      "title": "Тестовый Тест Тестович",
      "name": "Тест",
      "surname": "Тестовый",
      "patronymic": "Тестович",
      "phone": "79997788668",
      "email": "test_stand1@crm.mysmartflat.ru",
      "avatar": "https://files.mysmartflat.ru/10043.jpg",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1592365581,
      "last_active": "20.04.2021 17:59",
      "last_active_rfc": "2021-04-20T17:59:00+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1615553",
      "title": "тест паролей",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70012381567",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1624266146,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1832772",
      "title": "Руссу Иван Андреевич",
      "name": "Иван",
      "surname": "Руссу",
      "patronymic": "Андреевич",
      "phone": "79027937379",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1641775051,
      "last_active": "08.02.2022 10:03",
      "last_active_rfc": "2022-02-08T10:03:24+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1531782",
      "title": "мрир иторм снснс",
      "name": "иторм",
      "surname": "мрир",
      "patronymic": "снснс",
      "phone": "70002224245",
      "email": "gfg@fgy.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1603971196,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1503830",
      "title": "test5@crm.mysmartflat.ru",
      "name": "Test5@crm.mysmartflat.ru",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "test5@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1593493921,
      "last_active": "30.06.2020 13:12",
      "last_active_rfc": "2020-06-30T13:12:53+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1566227",
      "title": "Коза Машка ",
      "name": "Машка",
      "surname": "Коза",
      "patronymic": "",
      "phone": "70001007920",
      "email": null,
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1614230792,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1611650",
      "title": "шлот",
      "name": "Шлот",
      "surname": "",
      "patronymic": "",
      "phone": "70002106111",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1623400007,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1599425",
      "title": "Шрайбер Дмитрий Сергеевич",
      "name": "Дмитрий",
      "surname": "Шрайбер",
      "patronymic": "Сергеевич",
      "phone": "70009400000",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1620198383,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1448075",
      "title": "ТЕСТ ПРАВА МОГЕТ",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "mogetshtoli@example.com",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 7,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1572898",
      "title": "Светотест",
      "name": "Светотест",
      "surname": "",
      "patronymic": "",
      "phone": "70008202020",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1614480055,
      "last_active": "28.02.2021 13:11",
      "last_active_rfc": "2021-02-28T13:11:25+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1457780",
      "title": "Тестовый Илья",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "79223368875",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 7,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "25.10.2019 15:02",
      "last_active_rfc": "2019-10-25T15:02:24+05:00",
      "accounts": [],
      "comment": "g",
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1447846",
      "title": "тест аутентификации",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "sdfsdf@sdf.sdf",
      "avatar": "https://files.mysmartflat.ru/3979.jpg",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 19,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1623405940,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1611649",
      "title": "Шляпоногов Нагар Голович",
      "name": "Нагар",
      "surname": "Шляпоногов",
      "patronymic": "Голович",
      "phone": "70002106110",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1623399808,
      "last_active": "15.06.2021 15:17",
      "last_active_rfc": "2021-06-15T15:17:25+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1623233",
      "title": "Иванов Дмитрий Родионович",
      "name": "Дмитрий",
      "surname": "Иванов",
      "patronymic": "Родионович",
      "phone": "70000000000",
      "email": "",
      "avatar": "https://cndslctl.mysmartflat.ru/public-storage/684705d7-e72b-4b2d-8d97-5c5929ca9924.png",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1625562879,
      "last_active": "10.08.2021 11:39",
      "last_active_rfc": "2021-08-10T11:39:02+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1833301",
      "title": "Ван Су Ро",
      "name": "Су",
      "surname": "Ван",
      "patronymic": "Ро",
      "phone": "79644432774",
      "email": "puritanin@mail.ru",
      "avatar": "https://files.mysmartflat.ru/29499.jpg",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1641808668,
      "last_active": "18.02.2022 17:16",
      "last_active_rfc": "2022-02-18T17:16:20+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1560822",
      "title": "проверка прав2",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70008833761",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1611983766,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1500678",
      "title": "Тестовый Тест Тестович",
      "name": "Тест",
      "surname": "Тестовый",
      "patronymic": "Тестович",
      "phone": "777",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1591445059,
      "last_active": "26.06.2020 17:59",
      "last_active_rfc": "2020-06-26T17:59:38+05:00",
      "accounts": [],
      "comment": "autotest",
      "status": [
          "1",
          "3"
      ],
      "typeOwnership": "undefined",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "866775",
      "title": "ТЕСТ",
      "name": "Тест",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "5test@test.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 7,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "15.01.2021 10:20",
      "last_active_rfc": "2021-01-15T10:20:29+05:00",
      "accounts": [],
      "comment": "з3з",
      "status": [
          "1",
          "3",
          "5"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": "54",
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1493676",
      "title": "Борисов Дмитрий",
      "name": "Дмитрий",
      "surname": "Борисов",
      "patronymic": "Леонидович",
      "phone": "70000122849",
      "email": null,
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1586421180,
      "last_active": "30.11.2021 17:03",
      "last_active_rfc": "2021-11-30T17:03:19+05:00",
      "accounts": [],
      "comment": "Тестовый аккаунт",
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1662258",
      "title": "Модест",
      "name": "Модест",
      "surname": "",
      "patronymic": "",
      "phone": "70015537040",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1630066318,
      "last_active": "05.11.2021 16:33",
      "last_active_rfc": "2021-11-05T16:33:11+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1535187",
      "title": "Иванов Иван Иванович",
      "name": "Иван",
      "surname": "Иванов",
      "patronymic": "Иванович",
      "phone": "70000000112",
      "email": "ggsh@gwge.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 200,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1624294437,
      "last_active": "20.07.2021 18:26",
      "last_active_rfc": "2021-07-20T18:26:55+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1555878",
      "title": "Бусовиков Владос Алексеевич",
      "name": "Владос",
      "surname": "Бусовиков",
      "patronymic": "Алексеевич",
      "phone": "79991151205",
      "email": "v.buaovikov@gmail.com",
      "avatar": "https://files.mysmartflat.ru/11134.jpg",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1610944496,
      "last_active": "14.01.2022 11:59",
      "last_active_rfc": "2022-01-14T11:59:15+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1566404",
      "title": "Гладких Сергей",
      "name": "Сергей",
      "surname": "Гладких",
      "patronymic": "",
      "phone": "79504593631",
      "email": "gladkyh@ujin.tech",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1613104063,
      "last_active": "12.02.2021 11:41",
      "last_active_rfc": "2021-02-12T11:41:15+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1532561",
      "title": "Иммануилов Иммануил Константинович",
      "name": "Иммануил",
      "surname": "Иммануилов",
      "patronymic": "Константинович",
      "phone": "70009002552",
      "email": "zai@mail.ru",
      "avatar": "https://cndslctl.mysmartflat.ru/public-storage/6787afc1-1d22-48c0-b42c-85c03d85211c.png",
      "apartment": "ул. Несуществующая 42, кв. 5",
      "apartment_id": "21680",
      "apartment_number": "5",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 5",
      "building_id": "721",
      "created_at": 1604384143,
      "last_active": "22.11.2021 03:11",
      "last_active_rfc": "2021-11-22T03:11:23+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "undefined",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1599397",
      "title": "Шрайбер Дмитрий Сергеевич",
      "name": "Дмитрий",
      "surname": "Шрайбер",
      "patronymic": "Сергеевич",
      "phone": "70009400000",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1620186848,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1599332",
      "title": "Демо Демович",
      "name": "Демо",
      "surname": "",
      "patronymic": "Демович",
      "phone": "42349999999",
      "email": "u1d3www1@nail.ru",
      "avatar": "https://files.mysmartflat.ru/13079.png",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1620120678,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": "3412435ё2353",
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1657431",
      "title": "Тестовый",
      "name": "Тестовый",
      "surname": "",
      "patronymic": "",
      "phone": "70011568009",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1629630410,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1644492",
      "title": "Тестович Тест Тестович",
      "name": "Тест",
      "surname": "Тестович",
      "patronymic": "Тестович",
      "phone": "79824689049",
      "email": "zhikin.sv@gmail.com",
      "avatar": "https://files.mysmartflat.ru/24735.jpg",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1629061207,
      "last_active": "14.02.2022 10:43",
      "last_active_rfc": "2022-02-14T10:43:59+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1688363",
      "title": "testtesttest2crmmysmartflatru3 Testtesttest2crmmysmartflatru3 test",
      "name": "Testtesttest2crmmysmartflatru3",
      "surname": "testtesttest2crmmysmartflatru3",
      "patronymic": "test",
      "phone": "",
      "email": "testtesttest2@crm.mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 10,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1632112337,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1366827",
      "title": "Посохин Иваннн",
      "name": "Иваннн",
      "surname": "Посохин",
      "patronymic": "",
      "phone": "",
      "email": "dssdfsd@sdf.sdf",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 14,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "16",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1361976",
      "title": "Vb",
      "name": "Vb",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 14,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1",
          "4",
          "7"
      ],
      "typeOwnership": "2",
      "has_debts": false,
      "size": "43",
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1605118",
      "title": "Счетчики тест",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002105260",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1622025736,
      "last_active": "31.05.2021 18:02",
      "last_active_rfc": "2021-05-31T18:02:35+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1603967",
      "title": "Пропусков Пропуск Пропускович",
      "name": "Пропуск",
      "surname": "Пропусков",
      "patronymic": "Пропускович",
      "phone": "70002105240",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1621825681,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1361928",
      "title": "Посохин Иванn",
      "name": "Иванn",
      "surname": "Посохин",
      "patronymic": "",
      "phone": "12513451345",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 14,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": "2",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1589287",
      "title": "тест удаления квартир",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002104082",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1619080104,
      "last_active": "22.04.2021 18:20",
      "last_active_rfc": "2021-04-22T18:20:14+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1218103",
      "title": "Тест Приемка",
      "name": "Тест",
      "surname": "Приемка",
      "patronymic": "",
      "phone": "",
      "email": "500_rev_54@test.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 14,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "09.04.2019 14:14",
      "last_active_rfc": "2019-04-09T14:14:44+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "866779",
      "title": "Тест Тестович",
      "name": "Тест",
      "surname": "",
      "patronymic": "Тестович",
      "phone": "",
      "email": "deduhin@mysmartflat.ru",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 14,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "02.07.2019 14:39",
      "last_active_rfc": "2019-07-02T14:39:15+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "null",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1528650",
      "title": "Тестовый Тест Тестович",
      "name": "Тест",
      "surname": "Тестовый",
      "patronymic": "Тестович",
      "phone": "79999999993",
      "email": "z@z.ru",
      "avatar": "https://files.mysmartflat.ru/16805.jpg",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1602675286,
      "last_active": "13.09.2021 14:24",
      "last_active_rfc": "2021-09-13T14:24:23+05:00",
      "accounts": [],
      "comment": "акк для автотестов",
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1230443",
      "title": "Палабужев Владимир ",
      "name": "Владимир",
      "surname": "Палабужев",
      "patronymic": "",
      "phone": "79526462490",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 9",
      "apartment_id": "21684",
      "apartment_number": "9",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 14,
      "apartment_title": "ул. Несуществующая 42, кв. 9",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "18.10.2021 10:59",
      "last_active_rfc": "2021-10-18T10:59:51+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1448076",
      "title": "ТЕСТ ПРАВА НЕМОГЕТ",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "nemogetaga@example.com",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1563600",
      "title": "Тест Аренды НЕ ТРОГАТЬ",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002123344",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 1,
      "ownership_denominator": 2,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1612496674,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1534868",
      "title": "4080 datalost test",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70004134514",
      "email": "datalost@test.com",
      "avatar": "https://files.mysmartflat.ru/12627.png",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 3,
      "ownership_denominator": 8,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1605153311,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": "Три восьмых!!",
      "status": [
          "1"
      ],
      "typeOwnership": "2",
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1644883",
      "title": "Шрайбер Дмитрий Тест",
      "name": "Дмитрий",
      "surname": "Шрайбер",
      "patronymic": "Тест",
      "phone": "79323343243",
      "email": "dimshraj@gmail.com",
      "avatar": "https://cndslctl.mysmartflat.ru/public-storage/6985f20e-4629-4a29-aaad-2d7f8691faa6.png",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1628088928,
      "last_active": "11.02.2022 17:49",
      "last_active_rfc": "2022-02-11T17:49:20+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1622872",
      "title": "Погорелов Иван",
      "name": "Иван",
      "surname": "Погорелов",
      "patronymic": "",
      "phone": "70015151525",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1625489544,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1661727",
      "title": "Волков Тест Недап",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70015968954",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1630044011,
      "last_active": "27.08.2021 13:21",
      "last_active_rfc": "2021-08-27T13:21:22+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1599385",
      "title": "Шрайбер Дмитрий Сергеевич",
      "name": "Дмитрий",
      "surname": "Шрайбер",
      "patronymic": "Сергеевич",
      "phone": "70009400000",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1620184699,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1253535",
      "title": " C04A0CE428761C1E5EA80CAF89113AD6790F4A8E24886E41E50823DCE0B62D99 ",
      "name": "C04A0CE428761C1E5EA80CAF89113AD6790F4A8E24886E41E50823DCE0B62D99",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "25.12.2018 20:56",
      "last_active_rfc": "2018-12-25T20:56:41+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1661806",
      "title": "Тест Показаний _",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70000001122",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1630045698,
      "last_active": "27.08.2021 17:35",
      "last_active_rfc": "2021-08-27T17:35:03+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1432097",
      "title": " DEEBA69BA81D5C7A8438A40F66A5C6CE77D9CD329B2066D559D0C462F8620239 ",
      "name": "DEEBA69BA81D5C7A8438A40F66A5C6CE77D9CD329B2066D559D0C462F8620239",
      "surname": "",
      "patronymic": "",
      "phone": "",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "02.06.2019 15:33",
      "last_active_rfc": "2019-06-02T15:33:27+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1623234",
      "title": "Иванов Дмитрий Родионович",
      "name": "Дмитрий",
      "surname": "Иванов",
      "patronymic": "Родионович",
      "phone": "70000000000",
      "email": "",
      "avatar": "https://cndslctl.mysmartflat.ru/public-storage/684705d7-e72b-4b2d-8d97-5c5929ca9924.png",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1625562960,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "4"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1457725",
      "title": "Test Tyest Tyetsa",
      "name": "Tyest",
      "surname": "Test",
      "patronymic": "Tyetsa",
      "phone": "",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 10",
      "apartment_id": "21685",
      "apartment_number": "10",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 10",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "29.10.2019 16:33",
      "last_active_rfc": "2019-10-29T16:33:54+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1624397",
      "title": "Волкоff Владоss Сергеевич",
      "name": "Владоss",
      "surname": "Волкоff",
      "patronymic": "Сергеевич",
      "phone": "79124999966",
      "email": "demo_qa15@dema.com",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1625714559,
      "last_active": "03.03.2022 18:40",
      "last_active_rfc": "2022-03-03T18:40:39+05:00",
      "accounts": [],
      "comment": "тест",
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1862341",
      "title": "ер Еленааа ак",
      "name": "Еленааа",
      "surname": "ер",
      "patronymic": "ак",
      "phone": "70001010224",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1643685989,
      "last_active": "01.02.2022 13:35",
      "last_active_rfc": "2022-02-01T13:35:05+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1469162",
      "title": "Гасимов Руслан Альбертович",
      "name": "Руслан",
      "surname": "Гасимов",
      "patronymic": "Альбертович",
      "phone": "",
      "email": "gasimov@ujin.tech",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "03.03.2022 21:49",
      "last_active_rfc": "2022-03-03T21:49:37+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": "0",
      "has_debts": false,
      "size": "1",
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1678061",
      "title": "Рогов Федор Иванович",
      "name": "Федор",
      "surname": "Рогов",
      "patronymic": "Иванович",
      "phone": "70009845114",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1631065616,
      "last_active": "08.09.2021 11:48",
      "last_active_rfc": "2021-09-08T11:48:18+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1678077",
      "title": "Рогов Федор Иванович",
      "name": "Федор",
      "surname": "Рогов",
      "patronymic": "Иванович",
      "phone": "70009841451",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1631076578,
      "last_active": "08.09.2021 12:02",
      "last_active_rfc": "2021-09-08T12:02:45+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1528836",
      "title": "Пушевич",
      "name": "",
      "surname": "",
      "patronymic": "Пушевич",
      "phone": "70002010151",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1623408091,
      "last_active": "15.10.2020 16:40",
      "last_active_rfc": "2020-10-15T16:40:38+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1589277",
      "title": "Удаление квартир",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002104081",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1617860643,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1488436",
      "title": "Константин",
      "name": "",
      "surname": "Константин",
      "patronymic": "",
      "phone": "79991237880",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1584090931,
      "last_active": "12.02.2021 16:23",
      "last_active_rfc": "2021-02-12T16:23:10+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          1
      ],
      "readonly": false
  },
  {
      "id": "1862819",
      "title": "ел елена1 вал",
      "name": "елена1",
      "surname": "ел",
      "patronymic": "вал",
      "phone": "70001010230",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1643700261,
      "last_active": "01.02.2022 17:24",
      "last_active_rfc": "2022-02-01T17:24:32+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1595977",
      "title": "тест удаления квартир",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70002104082",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1619080104,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1759334",
      "title": "Новикова Анна Андреевна",
      "name": "Анна",
      "surname": "Новикова",
      "patronymic": "Андреевна",
      "phone": "70003522525",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1635490017,
      "last_active": "29.10.2021 17:51",
      "last_active_rfc": "2021-10-29T17:51:40+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "1"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1863069",
      "title": "ел Elena к",
      "name": "Elena",
      "surname": "ел",
      "patronymic": "к",
      "phone": "70001010234",
      "email": "",
      "avatar": "",
      "apartment": "25 Октября, 29, кв. 11",
      "apartment_id": "21697",
      "apartment_number": "11",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "25 Октября, 29, кв. 11",
      "building_id": "721",
      "created_at": 1643708016,
      "last_active": "07.02.2022 18:58",
      "last_active_rfc": "2022-02-07T18:58:45+05:00",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1568135",
      "title": "Тест Тест Тестович",
      "name": "Тест",
      "surname": "Тест",
      "patronymic": "Тестович",
      "phone": "70008555222",
      "email": "att@gmail.com",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 12",
      "apartment_id": "21698",
      "apartment_number": "12",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 12",
      "building_id": "721",
      "created_at": 1613538685,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1461544",
      "title": "Тестов Тест Тестович",
      "name": "Кортрос",
      "surname": "Азизов",
      "patronymic": "Тестович",
      "phone": "79124915027",
      "email": "",
      "avatar": "https://files.mysmartflat.ru/6221.jpg",
      "apartment": "ул. Несуществующая 42, кв. 12",
      "apartment_id": "21698",
      "apartment_number": "12",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 12",
      "building_id": "721",
      "created_at": 1581390126,
      "last_active": "17.09.2021 17:31",
      "last_active_rfc": "2021-09-17T17:31:39+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1588828",
      "title": "тест тест тест",
      "name": "тест",
      "surname": "тест",
      "patronymic": "тест",
      "phone": "70006952333",
      "email": "attik78@gmail.com",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 12",
      "apartment_id": "21698",
      "apartment_number": "12",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 12",
      "building_id": "721",
      "created_at": 1617773373,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1789226",
      "title": "Субтест 44",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70009951121",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 12",
      "apartment_id": "21698",
      "apartment_number": "12",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 12",
      "building_id": "721",
      "created_at": 1638180734,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1755806",
      "title": "субтест 22",
      "name": "",
      "surname": "",
      "patronymic": "",
      "phone": "70003271021",
      "email": "",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 12",
      "apartment_id": "21698",
      "apartment_number": "12",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 12",
      "building_id": "721",
      "created_at": 1635309277,
      "last_active": "",
      "last_active_rfc": "",
      "accounts": [],
      "comment": null,
      "status": [
          "3"
      ],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  },
  {
      "id": "1569114",
      "title": "тест тест тест",
      "name": "тест",
      "surname": "тест",
      "patronymic": "тест",
      "phone": "70008523111",
      "email": "atti86@gmail.com",
      "avatar": "",
      "apartment": "ул. Несуществующая 42, кв. 12",
      "apartment_id": "21698",
      "apartment_number": "12",
      "on_quarantine": 0,
      "ownership_numerator": 0,
      "ownership_denominator": 1,
      "apartment_title": "ул. Несуществующая 42, кв. 12",
      "building_id": "721",
      "created_at": 1613712494,
      "last_active": "03.02.2022 01:56",
      "last_active_rfc": "2022-02-03T01:56:06+05:00",
      "accounts": [],
      "comment": null,
      "status": [],
      "typeOwnership": null,
      "has_debts": false,
      "size": null,
      "rights": [
          2
      ],
      "readonly": false
  }
]

export const columns = [
  'ФИО',
  'Телефон',
  'Адрес',
  'Почта',
  'Размер доли',
  'Тип собственности',
  'Комментарий',
  'Последняя активность',
  'Статус',
  'Задолженность',
  'Дата последний квитанции',
];
